import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import ReduxProvider from "@/redux/ReduxProvider"
import ThemeProvider from "@/style/ThemeProvider"
import { Container } from "@mui/material"

export const metadata: Metadata = {
  title: "Bookstore",
  description: "Bookstore - Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider>
              <Container
                maxWidth="xl"
                disableGutters
                sx={{ padding: "12px 24px" }}
              >
                {children}
              </Container>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
